return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.colorscheme.nightfox-nvim"},
  { import = "astrocommunity.colorscheme.gruvbox-baby" },
  { import = "astrocommunity.colorscheme.rose-pine" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = 'astrocommunity.colorscheme.iceberg-vim'},
  { import = 'astrocommunity.colorscheme.kanagawa-nvim'},
  { import = 'astrocommunity.colorscheme.tokyonight-nvim'},
  { import = 'astrocommunity.colorscheme.mellow-nvim'},
  { import = 'astrocommunity.colorscheme.rose-pine'},
  { import = 'astrocommunity.colorscheme.github-nvim-theme'},
  { import = 'astrocommunity.colorscheme.everforest'},
  { -- further customize the options set by the community
    "catppuccin",
    opts = {
      integrations = {
        sandwich = false,
        noice = true,
        mini = true,
        leap = true,
        markdown = true,
        neotest = true,
        cmp = true,
        overseer = true,
        lsp_trouble = true,
        rainbow_delimiters = true,
      },
    },
  },
  { import = "astrocommunity.completion.copilot-lua" },
  { -- further customize the options set by the community
    "copilot.lua",
    opts = {
      suggestion = {
        keymap = {
          accept = "<C-l>",
          accept_word = false,
          accept_line = false,
          next = "<C-.>",
          prev = "<C-,>",
          dismiss = "<C/>",
        },
      },
    },
  },

  { import = "astrocommunity.git.git-blame-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.editing-support.zen-mode-nvim" },
  { import = "astrocommunity.git.diffview-nvim" },
  { import = "astrocommunity.motion.mini-surround"},
  { import = "astrocommunity.motion.hop-nvim"},
  -- { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.color.twilight-nvim" },
}
